keys:
  # - &xeno_at_zero age1lsfvx7nwct987yezqud0tt9y05yhmcquckf0kalfqwrqfuygnvhsr09d5g
  - &server_zero age1qwdngwfh5adnacezn35lzgnm7jcp0e7j6ts346ufkj58wwpy7d4qr6rm2m
creation_rules:
  - path_regex: secrets/hosts/zero/[^/\s]+.yaml$
    key_groups:
      - age:
          - *server_zero
